### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [AlanGreene/starter#20]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`Brewfile`](https://github.com/AlanGreene/starter/blob/ac16bc61ddc9b8917e6615cbeb4254ead064595d/osx/brew/Brewfile). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by AlanGreene** [comment]
Thanks for pointing this out, removed references to the old domain. I haven't used these scripts in a while so there are likely other things that need to be updated.
